---
title: "Plotly examples"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    
---

# Loading data

Added an extra line in the .yml file

We are agoing to look at the NYC airbnb data

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)
```

# Plotly plots

## Scatterplot

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    alpha = .5,
    type = "scatter", mode = "markers"
  )
```

## boxplot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    y = ~price, x = ~neighbourhood, color = ~neighbourhood,
    type = "violin", colors = "viridis")
```

## bar plot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, 
    type = "bar", color = ~neighbourhood, colors = "viridis")
```

# ggplotly

```{r}
ggp_scatter =
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price))+
  geom_point()

ggplotly(ggp_scatter)
```

